### ISSUE TITLE
Back to Game is Broken

### ISSUE THREAD

**Issue by Muscadinejelli** [bugcafe/bugcafe#2]
I was in a Cribbage game with Sandy:

Game Number | 240
-- | --
Game Type | cribbage
Game Name | Kelli/Sandy
Kelli | (muscadinejelli)
Sandy | (Sandy)
Last Play | Wednesday 06th of May 2020 08:03 PM UTC
Time Now | Wednesday 06th of May 2020 08:07 PM UTC

and wanted to read the entire message thread.  Clicked on Read Messages, read the messages, and then clicked on Back to Game.  The attached Word file is a picture of what I went back to.  While I'm always glad to win, it's even more fun to win one I didn't even play!  :D   

But I closed out of that, back to my manager, and thankfully the Cribbage game was still there waiting for me to play.
[Back to Game - wrong game.docx](https://github.com/bugcafe/bugcafe/files/4589250/Back.to.Game.-.wrong.game.docx)

**Comment by bugcafe** [comment]
This should be fixed now. Nice find! :)

**Comment by Muscadinejelli** [comment]
"I have not yet begun to break things!"
hehehe

    On Wednesday, May 6, 2020, 4:42:03 PM MDT, Lawrence Cooke <notifications@github.com> wrote:  
 
 


This should be fixed now. Nice find! :)
