### ISSUE TITLE
Letterbug info

### ISSUE THREAD

**Issue by smurfhuntter** [bugcafe/bugcafe#3]
When going to the letterbug games, click the information icon, the picture of the board does not appear only this sort of information as an example: 

Notice: Undefined variable: count in /usr/home/bc2020/public_html/bugcafe2020.com/start/letterbug/desc_board.php on line 88Notice: Undefined variable: count in /usr/home/bc2020/public_html/bugcafe2020.com/start/letterbug/desc_board.php on line 104Notice: Undefined variable: count in /usr/home/bc2020/public_html/bugcafe2020.com/start/letterbug/desc_board.php on line 118
--

this happens on all boards

**Comment by bugcafe** [comment]
this should be fixed, if you continue to have this issue , please let me know.
