### ISSUE TITLE
Cool - I broke it again!!

### ISSUE THREAD

**Issue by Muscadinejelli** [bugcafe/bugcafe#4]
Hi Mr. Bug!

I've been gone for a few weeks - personal stuff, bad place - but getting better.  So first thing catching up today I broke it!  Yay me!   👯‍♀️ 

I did a screenshot 

[Bugcafe Beta Broke It Rummibug.docx](https://github.com/bugcafe/bugcafe/files/4718108/Bugcafe.Beta.Broke.It.Rummibug.docx)

Basically, I clicked on Rummibug to see what it was and at the top of the page there's a link to "View Players" looking to play.  I clicked it and got the attached.

I renewed my month subscription before that with no issues!

Best always, 

Kelli - muscadinejelli

**Comment by bugcafe** [comment]
thanks for that, this should be fixed now.
